//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_WEBAPI_DOCUMENTATION_PRO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        public int idProduct { get; set; }
        public string name { get; set; }
        public string descrip { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> cant { get; set; }
    }
}
